name: Coverage Report

on:
  workflow_run:
    workflows: ['Coverage']
    types:
      - completed

jobs:
  report:
    runs-on: ubuntu-latest

    permissions:
      # Required to put a comment into the pull-request
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0

      - name: Download Artifacts
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
          name: coverage-${{ github.event.workflow_run.id }}
          path: coverage

      - name: Download main Artifacts
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
          name: coverage-main
          path: coverage-main

      - name: Report Coverage
        uses: davelosert/vitest-coverage-report-action@c4bbc33a89b7ace0e63d35f1f7d4bcee31155a73 # v2.13.0
        with:
          file-coverage-mode: all
          json-summary-compare-path: coverage-main/coverage-summary.json
