name: Coverage Report

on:
  workflow_run:
    workflows: ['Coverage']
    types:
      - completed

jobs:
  report:
    runs-on: ubuntu-latest

    permissions:
      # Required to put a comment into the pull-request
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Download Artifacts
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
          name: coverage-${{ github.event.workflow_run.id }}
          path: coverage

      - name: Download main Artifacts
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
          name: coverage-main
          path: coverage-main

      - name: Report Coverage
        uses: davelosert/vitest-coverage-report-action@7bf7d3c1b17a0e27c7e0d14190fb39168584bed2 # v2.8.1
        with:
          file-coverage-mode: all
          json-summary-compare-path: coverage-main/coverage-summary.json
